### ISSUE TITLE
Better readme

### ISSUE THREAD

**Issue by armandfardeau** [armandfardeau/slashershare#24]
## Better readme

The readme contributing part is not very clear, it could be great to have a part to explain how to execute test before pushing.

The tests pipeline is the following : 
* Rails test
* Rubocop

**Comment by alexandrechich** [comment]
@armandfardeau quand je fais 'rails test' j'ai 7 erreurs. Le point commun à chacune d'elles est 'Please install ImageMagick.'. Tu peux m'expliquer ce que c'est ?

**Comment by armandfardeau** [comment]
Hi @alexandrechich, you must install imagemagick as a system dependancie. It mentioned in the readme. Fell free to ask if you need any help
